# Generated by Django 4.2.6 on 2023-11-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=199)),
                ('email', models.CharField(max_length=199)),
            ],
        ),
        migrations.DeleteModel(
            name='Datamm',
        ),
    ]
