# Generated by Django 4.2.6 on 2023-11-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0002_mydata_delete_datamm'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
